apiVersion: apps/v1
kind: Deployment
metadata:
  name: saurabh-bms-app
  labels:
    app: bms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms-container
        image: swaksy7781/bms:latest
        ports:
        - containerPort: 3000
