apiVersion: v1
kind: Service
metadata:
  name: bms-service
  labels:
    app: bms
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodeport: 30085
  selector:
    app: bms
